### ISSUE TITLE
No such file or directory: '/tmp/README.md'

### ISSUE THREAD

**Issue by kimdn** [PNNL-CompBio/srpAnalytics#49]
I just tried
`docker run srp-analytics --test-morpho`

but I see

```
[]
Now zipping up1files
Traceback (most recent call last):
  File "dataQcBmd.py", line 268, in <module>
    main()
  File "dataQcBmd.py", line 248, in main
    tar.add('/tmp/'+fname)
  File "/usr/lib/python3.8/tarfile.py", line 1955, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/lib/python3.8/tarfile.py", line 1834, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/README.md'
 The initial X is infeasible.  Restart with its projection.
```

**Comment by sgosline** [comment]
this was a file path issue that i fixed in #54
